server:
  port: 8081

spring:
  security:
    user:
      name: admin
      password: admin

management:
  endpoints:
    web:
      exposure:
        include: '*'

springdoc:
  swagger-ui:
    path: /swagger-ui.html